---
- name: Container Runtime Setup (Podman/Docker)
  hosts: workstations
  become: true
  gather_facts: false
  pre_tasks:
    - name: Gather facts as unprivileged connection user
      ansible.builtin.setup:
      become: false
      tags: ["always"]
  roles:
    - role: b08x.devworkstation.containerd
      tags: ["containerd", "virt"]
