---
- name: Network Configuration
  hosts: workstations
  become: true
  gather_facts: false
  pre_tasks:
    - name: Gather facts as unprivileged connection user
      ansible.builtin.setup:
      become: false
      tags: ["always"]
  roles:
    - role: b08x.devworkstation.networking
      tags: ["networking", "system"]
